### ISSUE TITLE
Tabs and spaces

### ISSUE THREAD

**Issue by zkoppert** [AdvancedEnglish/CodingCoachZaKo#2]
https://github.com/AdvancedEnglish/CodingCoachZaKo/blob/2784d5c52e729c43e1b463eb39d4a0e9eabb5bfd/word_count.c#L23

It looks like you have a mix of tabs and spaces used for indenting. I recommend choosing one or the other and sticking with that. A mixture of both can make things not line up correctly based on which computer you are using.

**Comment by RMC-SP-BR** [comment]
ok, will do.  Thank you.
